fixedbig.go, fixedbig_test.go
`Benchmark_Lsh`
20000000	        98.2 ns/op
300000000	         4.69 ns/op compared to 7.27 ns/op
PASS
`Benchmark_Rsh`
20000000	        81.5 ns/op
300000000	         4.70 ns/op compared to 7.22 ns/op
PASS
=> optimize Lsh and Rsh

fixedbig.go, fixedbig_test.go
The separation of `n mod 64 = 0` case reduces the general number of comparisons.
The shift benchmarks only represent `192 < n < 256`, I tried to make benchmarks for the other cases too.
```
Benchmark_Lsh/big/n_eq_0-8         	20000000	       145 ns/op	     112 B/op	       2 allocs/op
Benchmark_Lsh/big/n_gt_192-8       	20000000	       146 ns/op	     128 B/op	       2 allocs/op
Benchmark_Lsh/big/n_gt_128-8       	10000000	       160 ns/op	     128 B/op	       2 allocs/op
Benchmark_Lsh/big/n_gt_64-8        	10000000	       149 ns/op	     112 B/op	       2 allocs/op
Benchmark_Lsh/big/n_gt_0-8         	10000000	       182 ns/op	     112 B/op	       2 allocs/op
Benchmark_Lsh/fixedbit/n_eq_0-8    	500000000	         3.35 ns/op	       0 B/op	       0 allocs/op
Benchmark_Lsh/fixedbit/n_gt_192-8 …
```
=> Lsh, Rsh: separate case n mod 64 = 0, extend benchmarks

fixedbig.go
```
if {
// A
} else if {
// B
} else if {
// C
} else if {
// D
} else {
// E
}
```
```
// A B C D E
// 1 2 3 4 4 (14 / 5 = 2.8)
```
```
if {
if {
// A
} else {
// B
}
} else if {
// C
} else if {
// D
} else {
// E
}
```
```
// A B C D E
// 2 2 2 3 3 (12 / 5 = 2.4)
```
=> Reduce the general number of comparisons

uint256.go, uint256_test.go
The biggest performance blocker is that there is a need to use `big.Int` because of the overflow. A trick could be to implement basic u512 support for multiplication operations for `Mul`.
=> Naive implementation of MulMod

uint256.go
It uses ToBig conversion but as I expect the use of it will be mostly for
debugging, so it shouldn't be a problem.
=> Implement fmt.Formatter interface

uint256.go
```
_Add/big-6               19.0ns ± 0%  19.0ns ± 0%     ~     (all equal)
_Add/uint256-6           3.73ns ± 0%  2.99ns ± 0%  -19.84%  (p=0.008 n=5+5)
_Sub/big-6               19.0ns ± 0%  19.0ns ± 0%     ~     (all equal)
_Sub/uint256-6           3.52ns ± 0%  2.99ns ± 0%  -15.06%  (p=0.029 n=4+4)
_Sub/uint256_of-6        3.81ns ± 0%  1.82ns ± 0%  -52.08%  (p=0.008 n=5+5)
_AddMod/large/big-6       211ns ± 0%   212ns ± 1%     ~     (p=0.079 n=4+5)
_AddMod/large/uint256-6  45.0ns ± 0%  39.5ns ± 0%  -12.18%  (p=0.000 n=5+4)
_AddMod/small/big-6      64.6ns ± 0%  64.6ns ± 0%     ~     (all equal)
_AddMod/small/uint256-6  21.6ns ± 0%  17.5ns ± 0%  -18.98%  (p=0.008 n=5+5)
```
Requires #27.
=> Simplify and optimize Add() and Sub()

uint256.go, uint256_test.go
This is used for `MulMod()` so `big.Mul()` is not needed any more (we still need `big.Mod()`).
This makes `small/uint256-6` case slower because we also removed the shortcut for `128x128` case.
The same procedure can be used to implement `Mul()`, but when `umul()` is used directly the final result is slower - optimizer is not clever enough to notice that the top 4 words in `umul()` are not used in the end.
Inner loop unroll removes any bounds checking.
```
_MulMod/large/big-6       384ns ± 1%   382ns ± 0%   -0.47%  (p=0.048 n=5+5)
_MulMod/large/uint256-6   802ns ± 0%   721ns ± 0%  -10.05%  (p=0.000 n=5+4)
_MulMod/small/big-6      93.9ns ± 0%  93.6ns ± 0%     ~     (p=0.103 n=5+5)
_MulMod/small/uint256-6  33.5ns ± 0%  41.1ns ± 0% …
```
=> Add "full" 256x256->512 multiplication

circle.yml, conversion.go, uint256.go, uint256_test.go
```
_Add/big-6               19.1ns ± 1%  19.0ns ± 0%     ~     (p=0.167 n=5+5)
_Add/uint256-6           2.99ns ± 0%  2.99ns ± 0%     ~     (all equal)
_Sub/big-6               19.0ns ± 0%  19.0ns ± 0%     ~     (all equal)
_Sub/uint256-6           2.99ns ± 0%  2.99ns ± 0%     ~     (all equal)
_Sub/uint256_of-6        1.82ns ± 0%  1.82ns ± 0%     ~     (all equal)
_Mul/big-6               88.9ns ± 0%  89.1ns ± 0%     ~     (p=0.135 n=5+5)
_Mul/uint256-6           15.5ns ± 0%  15.5ns ± 0%     ~     (all equal)
_Square/big-6            87.9ns ± 0%  87.9ns ± 1%     ~     (p=1.000 n=5+5)
_Square/uint256-6        16.0ns ± 0%  16.0ns ± 0%     ~     (all equal)
_And/big-6               12.4ns ± 0%  12.5ns ± 0%   +0.81%  (p=0.008 n=5+5) …
```
=> Faster and fixed big.Int -> uint256.Int conversion

conversion.go, conversion_test.go, uint256.go, uint256_test.go
```
ToBig/1word-6            64.9ns ± 0%  50.0ns ± 1%  -22.90%  (p=0.008 n=5+5)
ToBig/2words-6           90.6ns ± 0%  50.0ns ± 0%  -44.86%  (p=0.008 n=5+5)
ToBig/3words-6            111ns ± 0%    50ns ± 2%  -55.14%  (p=0.008 n=5+5)
ToBig/4words-6            126ns ± 0%    50ns ± 1%  -60.59%  (p=0.008 n=5+5)
_MulMod/large/uint256-6   628ns ± 0%   531ns ± 0%  -15.45%  (p=0.016 n=5+4)
```
1. Merge FromBig() and NewFromBig(). They were identical.
2. Adds more unit tests. Moves conversion tests to `conversion_test.go`.
3. Adds a benchmark for `ToBig()`.
4. Optimizes `ToBig()` in a similar way as `FromBig()` although in this case implementation is much simpler.
Probably the best to review commit by commit.
=> Cleanups and optimization of ToBig()

uint256.go, uint256_test.go
The `uint256` is now allocation free!
```
name                     old time/op    new time/op    delta
_Div/large/big-6            245ns ± 0%     245ns ± 0%      ~     (p=0.333 n=4+5)
_Div/large/uint256-6        139ns ± 0%      99ns ± 0%   -28.72%  (p=0.008 n=5+5)
_Div/small/big-6           69.0ns ± 1%    68.8ns ± 0%      ~     (p=0.159 n=5+5)
_Div/small/uint256-6       13.0ns ± 0%    13.1ns ± 0%      ~     (p=0.167 n=5+5)
_MulMod/large/big-6         388ns ± 0%     388ns ± 0%      ~     (p=1.000 n=5+5)
_MulMod/large/uint256-6     243ns ± 0%     204ns ± 0%   -16.05%  (p=0.008 n=5+5)
_MulMod/small/big-6        94.1ns ± 0%    93.9ns ± 0%      ~     (p=0.222 n=5+5)
_MulMod/small/uint256-6    40.4ns ± 0%    39.9ns ± 0%    -1.24%  (p=0.000 n=5+4)
MulMod/mod64-6              230ns ± 0%     186ns …
```
=> Eliminate allocations in division

circle.yml, codecov.yml, fuzz.go
1. Adds basic go-fuzz fuzzer - can be extended later.
2. Collects testing code coverage (both amd64 and 386) and uploads to codecov for visual report.
3. The fuzzer runs on CI for one minute. The corpus is preserved.
=> test: Fuzz with go-fuzz

div.go, uint256.go
This is based on [Improved division by invariant integers](https://gmplib.org/~tege/division-paper.pdf) and ported from https://github.com/chfast/intx.
The computation of reciprocal is single `DIV` x86_64 instruction, but there exist faster implementation (sneak peek in #39) but I left it for other time.
```
_Div/large/big-6          246ns ± 0%   245ns ± 0%   -0.49%  (p=0.016 n=4+5)
_Div/large/uint256-6     99.2ns ± 0%  83.3ns ± 0%  -16.07%  (p=0.008 n=5+5)
_Div/small/big-6         68.8ns ± 0%  68.8ns ± 0%     ~     (p=0.500 n=5+5)
_Div/small/uint256-6     13.1ns ± 0%  13.0ns ± 0%   -0.76%  (p=0.008 n=5+5)
_MulMod/large/big-6       388ns ± 0%   388ns ± 0%     ~     (p=0.167 n=5+5)
_MulMod/large/uint256-6   204ns ± 0%   153ns ± 0% …
```
=> Reciprocal-based 2by1 division procedure

benchmarks_test.go, conversion.go, uint256.go, uint256_test.go
```
name                      old time/op  new time/op  delta
_Add/single/uint256-6     3.08ns ± 0%  1.82ns ± 0%  -40.91%  (p=0.008 n=5+5)
_Sub/single/uint256-6     3.09ns ± 0%  1.82ns ± 0%  -41.10%  (p=0.008 n=5+5)
_Sub/single/uint256_of-6  1.82ns ± 0%  1.82ns ± 0%     ~     (all equal)
_Mul/single/uint256-6     15.9ns ± 0%  13.6ns ± 0%     ~     (p=0.079 n=4+5)
_Square/single/uint256-6  16.0ns ± 0%  14.6ns ± 0%   -8.27%  (p=0.008 n=5+5)
_And/single/uint256-6     1.67ns ± 5%  1.67ns ± 5%     ~     (p=1.000 n=5+5)
_Or/single/uint256-6      1.62ns ± 1%  1.61ns ± 1%     ~     (p=0.524 n=5+5)
_Xor/single/uint256-6     1.61ns ± 0%  1.66ns ± 5%     ~     (p=0.556 n=4+5)
_Cmp/single/uint256-6     2.96ns ± 0%  2.58ns ± 0%     ~     (p=0.079 n=4+5)
Lt/large/uint256-6        5.29ns ± 0%  2.53ns ± …
```
=> Optimizations

uint256.go
1. Fully unroll `umul()` implementation (the first commit does majority of that, the second is small tuning giving small improvement, but affects readability).
2. The use the `umul()` implementation to implement `Mul()`.
3. Also optimize `Squared()`.
```
name                      old time/op  new time/op  delta
_Mul/single/big-6          210ns ± 1%   210ns ± 0%     ~     (p=1.000 n=10+10)
_Mul/single/uint256-6     36.3ns ± 0%  18.0ns ± 0%  -50.37%  (p=0.000 n=10+10)
_Square/single/big-6       207ns ± 0%   207ns ± 1%     ~     (p=0.108 n=9+10)
_Square/single/uint256-6  34.9ns ± 0%  13.7ns ± 0%  -60.71%  (p=0.000 n=9+9)
_Exp/large/big-6          47.5µs ± 1%  47.6µs ± 1%     ~     (p=0.393 n=10+10)
_Exp/large/uint256-6      14.4µs ± 0%   6.8µs ± 0%  -52.91%  (p=0.000 n=10+9)
_Exp/small/big-6 …
```
=> Optimize multiplication

uint256_test.go
This allows test any binary op using predefined test cases. In preparation for testing bitwise ops.
=> test: Create generic test runner for binary ops

benchmarks_test.go
This also eliminates the 1 allocation per loop iteration in benchmarks
for `big.Int`.
```
name                     old time/op    new time/op    delta
Mul/single/uint256-6       18.0ns ± 1%    17.0ns ± 1%    -5.99%  (p=0.000 n=20+20)
Mul/single/big-6            211ns ± 0%     130ns ± 0%   -38.39%  (p=0.000 n=16+16)
Square/single/uint256-6    13.7ns ± 0%    12.9ns ± 1%    -5.77%  (p=0.000 n=18+20)
Square/single/big-6         204ns ± 0%     125ns ± 1%   -38.59%  (p=0.000 n=13+18)
name                     old alloc/op   new alloc/op   delta
Mul/single/uint256-6        0.00B          0.00B           ~     (all equal)
Mul/single/big-6            96.0B ± 0%      0.0B       -100.00%  (p=0.000 n=20+20)
Square/single/uint256-6     0.00B          0.00B           ~     (all equal) …
```
=> test: Cleanup Mul / Square benchmarking code

uint256_test.go
All this to test the case where addition does not overflow in `AddMod()` and regular `Mod()` can be used.
https://codecov.io/gh/holiman/uint256/compare/master...tests/changes#L179
=> test: Add TestTernOp() for {Add,Mul}Mod ops

conversion.go
Replace panic() checking for architecture other than 32 or 64 bit
with compilation-time checks using uint constant underflow trick.
=> Replace panic() with compilation-time check

AUTHORS, COPYING
Small tweaks to license text layout and one change OWNER -> HOLDER
as in https://choosealicense.com/licenses/bsd-3-clause/.
Added "BSD 3-Clause License" headline.
Changed Copyright line to "Copyright 2020 uint256 Authors"
as in https://opensource.org/licenses/BSD-3-Clause.
The "All rights reserved" omitted as it has no use nowadays.
=> Clean up license text

uint256.go
```
Mul/single/uint256-8     8.23ns ± 2%  6.90ns ± 1%  -16.11%  (p=0.000 n=10+9)
Mul/single/big-8         64.5ns ± 1%  62.8ns ± 1%   -2.65%  (p=0.000 n=9+9)
_Exp/large/big-8         23.7µs ± 1%  23.7µs ± 1%     ~     (p=0.896 n=10+10)
_Exp/large/uint256-8     3.34µs ± 1%  2.72µs ± 3%  -18.63%  (p=0.000 n=8+10)
_Exp/small/big-8         7.12µs ± 2%  7.09µs ± 0%     ~     (p=0.345 n=10+9)
_Exp/small/uint256-8      283ns ± 1%   229ns ± 1%  -19.22%  (p=0.000 n=9+10)
Square/single/uint256-8  6.27ns ± 1%  5.14ns ± 1%  -17.91%  (p=0.000 n=10+10)
Square/single/big-8      60.0ns ± 2%  60.0ns ± 1%     ~     (p=0.781 n=10+10)
```
=> Optimise squared, Mul, and Exp

uint256.go, uint256_test.go
I deliberately used full umul for clarity; this operation can be optimised later if need be.
=> MulOverflow

benchmarks_test.go, uint256.go
Adds a benchmarks and simplifies/improves `MulOverflow` a bit
```
name                          old time/op    new time/op    delta
MulOverflow/single/uint256-6    25.1ns ± 3%    23.0ns ± 1%  -8.22%  (p=0.016 n=5+4)
MulOverflow/single/big-6        77.0ns ±13%    75.7ns ± 4%    ~     (p=0.937 n=5+5)
name                          old alloc/op   new alloc/op   delta
MulOverflow/single/uint256-6     0.00B          0.00B         ~     (all equal)
MulOverflow/single/big-6         0.00B          0.00B         ~     (all equal)
name                          old allocs/op  new allocs/op  delta
MulOverflow/single/uint256-6      0.00           0.00         ~     (all equal)
MulOverflow/single/big-6          0.00           0.00         ~     (all equal)
```
=> optimize + benchmark muloverflow

uint256.go, uint256_test.go
Some methods check mod 0-ness inside, some outside. Make it consistent across all methods at API entry point.
=> Handle mod 0 uniformly for all API methods

benchmarks_test.go, conversion.go, conversion_test.go
This PR adds some more marshalling methods. If we want to replace `big.Int` and `hexutil.Big` with `uint256.Int` in go-ethereum, these methods are needed. 
```
Benchmark_EncodeHex/large/uint256-6             10843225                97.2 ns/op            80 B/op          1 allocs/op
Benchmark_EncodeHex/large/big-6                  6547092               190 ns/op             139 B/op          2 allocs/op
Benchmark_DecodeHex/large/uint256-6              9983671               118 ns/op              32 B/op          1 allocs/op
Benchmark_DecodeHex/large/big-6                 10242964               128 ns/op              32 B/op          1 allocs/op
```
=> conversion: add various marshalling methods

benchmarks_test.go, uint256.go
We can do it with a single comparison. The speed up for the bad case is ~30%.
```
name                   old time/op    new time/op    delta
_Cmp/single/big-8        13.1ns ± 4%    13.1ns ± 2%     ~     (p=0.887 n=10+9)
_Cmp/single/uint256-8    5.40ns ± 3%    4.69ns ± 3%  -13.17%  (p=0.000 n=10+9)
name                   old alloc/op   new alloc/op   delta
_Cmp/single/big-8         0.00B          0.00B          ~     (all equal)
_Cmp/single/uint256-8     0.00B          0.00B          ~     (all equal)
name                   old allocs/op  new allocs/op  delta
_Cmp/single/big-8          0.00           0.00          ~     (all equal)
_Cmp/single/uint256-8      0.00           0.00          ~     (all equal)
```
=> Optimize comparison in `Cmp()`

AUTHORS, benchmarks_test.go
Separate PR for benchmark changes separated out from #86 as requested
=> benchmarks: use least non negative residue of the addend for each modulus when testing AddMod

conversion_test.go
This PR should bring back the test coverage to 100%
=> tests: rlp encoding test

benchmarks_test.go
Updated benchmarks to provide the baseline for #86
=> Benchmark updates

benchmarks_test.go, fuzz.go, uint256.go, uint256_test.go
This PR implements `Sqrt`, and closes #100. 
```
BenchmarkSqrt/single/uint256-6           1958528               603.8 ns/op             0 B/op          0 allocs/op
BenchmarkSqrt/single/uint256-6           1942036               667.9 ns/op             0 B/op          0 allocs/op
BenchmarkSqrt/single/uint256-6           1999359               607.8 ns/op             0 B/op          0 allocs/op
BenchmarkSqrt/single/uint256-6           1914327               587.4 ns/op             0 B/op          0 allocs/op
BenchmarkSqrt/single/uint256-6           2010532               610.4 ns/op             0 B/op          0 allocs/op
BenchmarkSqrt/single/big-6                539826              4824 ns/op             528 B/op          7 allocs/op
BenchmarkSqrt/single/big-6                585172 …
```
=> implement Sqrt()

benchmarks_test.go, uint256_test.go
Rename big.Int reference operator implementations with prefix "big" and unify their usage in random tests.
=> test: Refactor tests

uint256.go, uint256_test.go
I wanted to make `udivrem()` more robust by making it handle the case where nominator is smaller than divisor (currently it will panic weirdly in this case).
I'm testing the change though `TestRandomDiv` and `TestRandomMod` where `divraw` and `modraw` wrappers are provided.
The `modraw` fails a test when a param and result are aliased. I have not been able to figure out the cause of the problem so far.
=> Handle nominator smaller than divisor in udivrem()

AUTHORS, benchmarks_test.go, fuzz.go, oss-fuzz.sh, uint256.go, uint256_test.go
`(x * y) / denominator` is the most common case that cannot be calculated with full precision by normal methods `z.Mul(x, y).Div(z, denominator)` 
ex. `(max_uint256 * 2)/10` 
an overflow occurs when you try to calculated by normal methods, but the result is smaller than `max_uint256`.
`MulDivOverflow()` is 512-bit multiplication and 512-bit by 256-bit division.
returns The 256-bit result and overflow occurred. 
inspired and realworld use-case from UniswapV3
[https://github.com/Uniswap/v3-core/blob/main/contracts/libraries/FullMath.sol](url)
```
BenchmarkMulDivOverflow/small/uint256-8         	491599033	         2.297 ns/op	       0 B/op	       0 allocs/op
BenchmarkMulDivOverflow/div64/uint256-8         	512714014	         2.351 ns/op	       0 B/op	       0 allocs/op …
```
=> Add Muldiv()

uint256.go, uint256_test.go
DivMod() sets z to the quotient x div y and m to the modulus x mod y and returns the pair (z, m) for y != 0.
If y == 0, both z and m are set to 0 (OBS: differs from the big.Int).
Closes https://github.com/holiman/uint256/issues/103.
=> Add DivMod()

uint256.go
uint256 master:
```
BenchmarkAddMod/small/uint256-4                 71864941                14.78 ns/op
BenchmarkAddMod/mod64/uint256-4                 45851817                23.58 ns/op
BenchmarkAddMod/mod128/uint256-4                23512131                49.20 ns/op
BenchmarkAddMod/mod192/uint256-4                22141264                53.37 ns/op
BenchmarkAddMod/mod256/uint256-4                55604551                21.38 ns/op
```
this PR:
```
BenchmarkAddMod/small/uint256-4                 74203911                14.75 ns/op
BenchmarkAddMod/mod64/uint256-4                 44762869                23.61 ns/op
BenchmarkAddMod/mod128/uint256-4                22504081                49.59 ns/op
BenchmarkAddMod/mod192/uint256-4                21490502                52.70 ns/op …
```
=> optimize AddMod where modulus is 4-limbs wide and x/y highest limb is  less than or equal to modulus highest limb

.gitignore, conversion.go, conversion_test.go
this pr has the following:
1. the call to strings.SplitN in my original implementation is replaced with Index, and the function is changed to avoid the extra allocation
2. makes the []byte variant properly parse scientific notation. 
3. adds pprof debug output to gitignore
4. adds benchmark to bench the scan function
=> conversion: optimize `Scan()` scientific scanning

conversion.go, conversion_test.go
This PR allows the second form (last two lines) along side the current form (first two lines) of initializing new ints from bigs.
```go
var (
costCap, _   = uint256.FromBig(item.Tx.Cost())
gasTipCap, _ = uint256.FromBig(item.Tx.GasTipCap())
)
meta := &blobTxMeta{
id:            id,
size:          size,
nonce:         item.Tx.Nonce(),
costCap:       costCap,
gasTipCap:     gasTipCap,
gasFeeCap:     uint256.MustFromBig(item.Tx.GasFeeCap()),
blobGasFeeCap: uint256.MustFromBig(item.Tx.BlobGasFeeCap()),
}
```
Panics can only be captured when a goroutine is unwinding, hence why the messy construct in the tests. Also, it would have been a tad cleaner to wait on the panic with `sync.WaitGroup` vs a channel, but the channel approach introducing a dependency on `sync`.
=> add `MustFromBig` for nicer struct initialization

circle.yml, conversion.go, conversion_test.go, decimal.go
This PR implements the `Dec` method 'natively', and adds the API-method `PrettyDec`.
```golang
// Dec returns the decimal representation of z.
func (z *Int) Dec() string
// PrettyDec returns the decimal representation of z, with thousands-separators.
func (z *Int) PrettyDec(separator byte) string 
```
It also adds benchmarks and a new fuzz-test for the changed methods. 
```
BenchmarkDecimal/ToDecimal/uint256-8         	   12324	    102673 ns/op	   11344 B/op	     248 allocs/op
BenchmarkDecimal/ToPrettyDecimal/uint256-8   	    9595	    110235 ns/op	   14720 B/op	     251 allocs/op
BenchmarkDecimal/ToDecimal/big-8             	   10000	    133930 ns/op	   31920 B/op	     594 allocs/op
```
=> conversion: add `PrettyDec`, optimize `Dec`, add benchmarks and fuzzing

conversion.go, conversion_test.go
Ref: https://github.com/holiman/uint256/issues/123 
This PR implements 
```
// Float64 returns the float64 value nearest to x.
//
// Note: The `big.Float` version of `Float64` also returns an 'Accuracy', indicating
// whether the value was too small or too large to be represented by a
// `float64`. However, the `uint256` type is unable to represent values
// out of scope (|x| < math.SmallestNonzeroFloat64 or |x| > math.MaxFloat64),
// therefore this method does not return any accuracy.
//
// OBS! Currently, this method is not optimized: but uses big.Int and big.Float.
func (z *Int) Float64() float64
```
Implementing `Float64` makes it possible to use e.g. the logarithm functions in the `math` package. 
Todo:
=> implement `Float64() float64`

conversion.go, conversion_test.go
This is perhaps a debatable change, but may be more logical than originally anticipated.
In some places, having a `nil` as a `big.Int` or `uint256.Int` might make sense (e.g. an optional and non-initialized field). In those cases, converting between the two across older/newer code might be necessary. In it's current incarnation, the uint256 library will crash, so all optional nils need to be special cased.
IMHO this should not be necessary. If a uint256 should not be nil, but a nil big int is passed, then I assume the code later will crash anyway on some uint256 accessor method whether we crash at the conversion or not, so it's not like we're silently swallowing up errors. On the other hand, allowing the nils to be converted back and forth reduces the error potential of forgetting to …
=> Allow converting between nil big.Int and nil uint256.Int

benchmarks_test.go, uint256.go, uint256_test.go
This PR implements
```
// CmpBig compares z and x and returns:
//
//	-1 if z <  x
//	 0 if z == x
//	+1 if z >  x
func (z *Int) CmpBig(x *big.Int) (r int) 
```
After some benchmarking, it turned out that converting from big to `Int` was not significantly slower than e.g pre-checking the `BitLength`, so I went with that in the end.  
Closes https://github.com/holiman/uint256/issues/135
=> Implement `CmpBig`

README.md
turbo-geth is renamed to erigon in 2021.
=> README: rename turbo-geth to erigon

uint256.go
Using 4 local uint64 variable enables register allocation instead of memory allocation for uint256. 
This improve the performance of `Mul`, `squared`, `Exp` about 40%.
Running
```
go test ./...
```
returns
```
ok  	github.com/holiman/uint256	0.978s
```
```
go test -run - -bench BenchmarkExp -benchmem -count=10 >/tmp/old
```
`squared` benchmark:
```
goos: linux
goarch: amd64
Square/single/uint256-16   7.235n ± 3%   4.304n ± 1%  -40.52% (p=0.000 n=10)
Square/single/big-16       36.73n ± 1%   36.72n ± 1%        ~ (p=0.782 n=10)
geomean                    16.30n        12.57n       -22.89%
│     old …
```
=> uint256: optimize Mul, squared and Exp

uint256.go
Following Div and Mod, this commit adds shortcut trivial cases for DivMod.
=> uint256: optimize DivMod

benchmarks_test.go
When I saw the original BenchmarkMulDivOverflow shows MulDivOverflow(uint256) is 2 ns and MulDivOverflow(big.Int) is 13 ns,
I knew there's a problem, because div alone would have taken around 20 ns for uint256.
The computation is like this:
```
int256SamplesLt[j]           int256SamplesLt[j]
int256SamplesLt[j] * -------------------- ...... * -------------------
int256Samples[j]             int256Samples[j]
```
where int256SamplesLt[j] < int256Samples[j].
So within around 1000 iterations, x is reduced to zero, and when x is zero, the function MulDivOverflow directly returns zero, skipping the computation.
=> benchmarking: fix BenchmarkMulDivOverflow

benchmarks_test.go, uint256.go, uint256_test.go
The main difference is
```
z[0] = (number & (0xff00000000000000 >> offset)) >> (56 - offset)
```
vs
```
z[0] = (number >> (56 - offset)) & 0xff
```
------------------------
```
go test ./...
```
returns
```
ok  	github.com/holiman/uint256	0.972s
```
code:
```
func BenchmarkByte(bench *testing.B) {
a := new(Int).SetBytes(hex2Bytes("f123456789abcdeffedcba9876543210f2f3f4f5f6f7f8f9fff3f4f5f6f7f8f9"))
n := NewInt(16)
result := new(Int)
bench.ResetTimer()
for i := 0; i < bench.N; i++ {
result.Set(a)
result.Byte(n)
}
}
```
```
goos: linux
goarch: amd64
│     old     │                new                 │
│   sec/op    │   sec/op     vs base               │
Byte-16   2.849n ± 2%   2.571n ± 2%  -9.77% (p=0.000 …
```
=> uint256: optimize Byte

uint256.go
Sorry. I miss a special case `z == byteNum`,  that is `z.ExtendSign(x,z)`.
=> uint256: fix ExtendSign

conversion_test.go, uint256.go
```
go test ./...
```
```
ok  	github.com/holiman/uint256	1.367s
```
```
goos: linux
goarch: amd64
AddMod/small/uint256-16    6.292n ± 1%   6.309n ± 1%        ~ (p=0.123 n=10)
AddMod/mod64/uint256-16    10.07n ± 1%   10.02n ± 1%   -0.55% (p=0.049 n=10)
AddMod/mod128/uint256-16   19.14n ± 1%   19.16n ± 1%        ~ (p=0.271 n=10)
AddMod/mod192/uint256-16   20.88n ± 2%   21.09n ± 1%   +1.03% (p=0.050 n=10)
AddMod/mod256/uint256-16   9.728n ± 2%   6.460n ± 1%  -33.59% (p=0.000 n=10)
AddMod/small/big-16        25.80n ± 0%   25.85n ± 0%        ~ (p=0.071 n=10)
AddMod/mod64/big-16        30.18n ± 1% …
```
=> uint256: optimize AddMod

uint256.go
Minor tweek of the code. Not sure where the boost comes from. But it does improve around 10% in my two x86-64 machines.
godbolt links:
old:  https://go.godbolt.org/z/z8vqhG9r7
new: https://go.godbolt.org/z/M17Ycfzxx
```
go test ./...
```
```
ok  	github.com/holiman/uint256	1.380s
```
```
goos: linux
goarch: amd64
Mul/single/uint256-16   4.239n ± 2%   3.725n ± 1%  -12.14% (p=0.000 n=10)
Mul/single/big-16       37.05n ± 1%   36.96n ± 2%        ~ (p=0.403 n=10)
geomean                 12.53n        11.73n        -6.38%
```
```
goos: linux
goarch: amd64
cpu: Intel Core …
```
=> uint256: minor improvement for Mul

uint256.go
Since functions `addTo` and `subMulTo` are in a for loop inside `udivremKnuth`, reducing bounds check in them should result in an observable performance boost.
`len(y) > 0` should be guaranteed by those respective non-zero checks for divisors inside `Div`, `Mod`, `AddMod`, etc.
```
go test ./...
```
```
ok  	github.com/holiman/uint256	1.375s
```
```
go test -run - -bench 'Mod|Div' -count 10 -timeout 40m >/tmp/old
go test -run - -bench 'Mod|Div' -count 10 -timeout 40m >/tmp/new
benchstat old new | grep -v big
```
```
goos: linux
goarch: amd64
Div/small/uint256-16               3.121n ± 1%   3.087n ± …
```
=> uint256: optimize div-related functions by reducing bounds check

binary_test.go, decimal.go, uint256.go, uint256_test.go
The functions `Div`, `SDiv` and `MulDivOverflow` don't need the remainder, so we change the api of `udivrem` to pass nil to skip the last part of the computatoin of `rem`. This PR doesn't affect the computation of quotient `quot`.
```
go test ./...
```
```
ok  	github.com/holiman/uint256	1.366s
```
```
goos: linux
goarch: amd64
│     old      │                 new                 │
│    sec/op    │   sec/op     vs base                │
Div/small/uint256-16                3.105n ± 0%   3.105n ± 1%        ~ (p=0.988 n=10)
Div/mod64/uint256-16                21.57n ± 2%   21.20n ± 2%   -1.72% (p=0.017 n=10)
Div/mod128/uint256-16               38.65n ± 2%   37.28n ± 1%   -3.53% (p=0.000 n=10) …
```
=> uint256: optimize div-related functions by removing unnecessary computation

mod.go, uint256.go
The api of `reduce4` is changed to reduce array copies.
1. The function `reduce4` doesn't change the values of its parameters `x`, `m`, and `mu`. So it's fine to pass by pointers.
2. In the case of `z == m` (They are alias), `m` is used before `z`, and `z` is only written in the last step. So this is fine too.
```
goos: linux
goarch: amd64
MulMod/small/uint256-16     15.84n ± 2%   15.63n ± 1%   -1.33% (p=0.049 n=10)
MulMod/mod64/uint256-16     29.44n ± 1%   29.09n ± 2%   -1.17% (p=0.030 n=10)
MulMod/mod128/uint256-16    51.92n ± 1%   52.62n ± 2%        ~ (p=0.183 n=10)
MulMod/mod192/uint256-16 …
```
=> uint256: optimize MulMod, MulModWithReciprocal

benchmarks_test.go, uint256.go
`Lt` is branchless and can be inlined, while `Cmp` has two `if` branches and can not be inlined. So `Lt` is better.
To check if a simple function can be inlined or not in golang, run
```
go build -gcflags='-m -m' |& grep Lt
```
Learn this trick a few days ago.
```
goos: linux
goarch: amd64
Mod/small/uint256-16       4.041n ± 2%   2.865n ± 1%  -29.10% (p=0.000 n=10)
Mod/mod64/uint256-16       22.68n ± 1%   21.39n ± 2%   -5.69% (p=0.000 n=10)
Mod/mod128/uint256-16      39.82n ± 1%   38.23n ± 1%   -4.01% (p=0.000 n=10)
Mod/mod192/uint256-16      36.37n ± 1%   34.69n ± 2%   -4.62% (p=0.000 n=10) …
```
=> uint256: optimize Mod, DivMod, AddMod

conversion.go, conversion_test.go
This fixes the append vs overwrite part of https://github.com/holiman/uint256/issues/170 .
However, this is technically a breaking change. On the other hand, the way it now works is incompatible with the fastssz encoding library. And since nobody has raised this earlier, I assume nobody has really used it in production.  
So, should be fine to merge, on that reasoning. 
(?)
=> conversion: replace `MarshalSSZTo` with `MarshalSSZAppend` and `MarshalSSZInto`

benchmarks_test.go, conversion.go, conversion_test.go
Fixes https://github.com/holiman/uint256/issues/176
TL;DR: `ToBig` does 2x32 byte allocations. Once to create a new big.Int and a second time to seed the contents of the big.Int. This PR adds `IntoBig` (to avoid breaking the API) which takes an input big.Int, and if it has a large enough internal buffer, it will use that for conversion instead of reallocating.
If the big.Int is nil, it will be allocated (32 byte) and if it's not large enough, it's data space will be allocated (32 byte).
Bechmarks:
```
goos: darwin
goarch: arm64
BenchmarkToBig/1word-12         	35593915	        33.95 ns/op	      64 B/op	       2 allocs/op
BenchmarkToBig/2words-12        	35652079	        33.95 ns/op	      64 B/op	       2 allocs/op
BenchmarkToBig/3words-12        	36683552 …
```
=> conversion: introduce 0-alloc IntoBig method

ternary_test.go, uint256.go
This PR fixes https://github.com/holiman/uint256/issues/178, it also adds tests for it. While adding the tests, I found that the proposed fix in #179 was insufficient - we generally need to un-alias `z` and `m` too, since they're both used as returnvalues. 
Otherwise this PR also contains some `go fmt` changes.
=> divmod: fix aliasing error, add tests

conversion.go, conversion_test.go, decimal.go
The json-unmarshalling from decimal form inorrectly invoked fromDecimal, instead of SetFromDecimal. The former assumes that the input has already been validated, and thus does not throw errors on overflow.
Closes #184
=> conversion: fix unmarshalling overflow

benchmarks_test.go, uint256.go, uint256_test.go
Make WriteToArray32 and WriteToArray20 use PutUint64 like in Bytes32 and Bytes20 to remove all branches and increase the number of bytes per 1 load/store to 8 bytes.
```
goos: linux
goarch: amd64
cpu: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
│    old.txt     │                new.txt                │
│     sec/op     │    sec/op      vs base                │
WriteToArray20-8   31.8000n ± 15%   0.7819n ± 17%  -97.54% (p=0.000 n=10)
WriteToArray32-8    57.640n ± 22%    1.050n ± 18%  -98.18% (p=0.000 n=10)
geomean              42.81n         0.9059n        -97.88%
```
By changing Memory.Set32 in go-ethereum to use new WriteToArray32 we can reduce a memory copy which makes OpMstore faster.
The patch
```
diff --git a/core/vm/memory.go b/core/vm/memory.go …
```
=> uint256: optimize WriteToArray

benchmarks_test.go, uint256.go
full benchstat:
```goos: linux
goarch: amd64
cpu: Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
│    old.txt     │               new.txt               │
│     sec/op     │   sec/op     vs base                │
Exp/large/big-2               21.01µ ± 8%   21.60µ ± 5%        ~ (p=0.393 n=10)
Exp/large/even/big-2          6.033µ ± 6%   6.133µ ± 6%        ~ (p=0.353 n=10)
Exp/large/uint256-2           2.311µ ± 4%   2.348µ ± 5%        ~ (p=0.315 n=10)
Exp/large/even/uint256-2   2279.500n ± 4%   6.894n ± 3%  -99.70% (p=0.000 n=10)
Exp/small/big-2               7.050µ ± 8%   6.753µ ± 3%        ~ (p=0.579 n=10)
Exp/small/even/big-2          1.979µ ± 6%   1.982µ ± 6%        ~ (p=0.684 n=10)
Exp/small/uint256-2           200.0n ± 4%   205.8n ± 5%        ~ (p=0.853 …
```
=> optimize `Exp` for even bases

uint256.go
Internal shift helper functions like `lsh64`, `lsh128`, etc. were returning `*Int` even though these return values were never used. This PR removes the unnecessary return values to improve code clarity.
The affected methods are:
- lsh64
- lsh128  
- lsh192
- rsh64
- rsh128
- rsh192
- srsh64
- srsh128
- srsh192
This is a minor cleanup change with no functional impact since these are internal functions and their return values were not being used.
=> internal: remove unused return values from shift-helpers
